-- Add PL/pgSQL extension
CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;
COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';

-- Create roles
CREATE USER test WITH ENCRYPTED PASSWORD 'test';
CREATE USER keycloak WITH ENCRYPTED PASSWORD 'keycloak';

-- Create databases
CREATE DATABASE test OWNER test;
CREATE DATABASE keycloak OWNER keycloak;

CREATE ROLE barman PASSWORD 'barman' SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN;
CREATE ROLE streamingbarman PASSWORD 'streamingbarman' NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN REPLICATION;
